server:
  session-timeout: 1800
  port: 8082
spring:
  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://192.168.128.155:3306/bootdo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache